apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tunzxklhv-go
  janus-idp.io/tekton: tunzxklhv-go
  backstage.io/kubernetes-id: tunzxklhv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tunzxklhv-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
