apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tunzxklhv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tunzxklhv-go 
  name: tunzxklhv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tunzxklhv-go 
